language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'see-spot-follow' ]; then cd .. && eval "mv $currentfolder see-spot-follow" && cd see-spot-follow; fi
